[fuzz.metrics]
enabled = true

[[fuzz.programs]]
address = "BXG5KG57ef5vgZdA4mWjBYfrFPyaaZEvdHCmGsuj7vbq"
program = "target/deploy/sss_token.so"

[[fuzz.programs]]
address = "B9HzG9fuxbuJBG2wTSP6UmxBSQLdaUAk62Kcdf41WxAt"
program = "target/deploy/sss_transfer_hook.so"
