[fuzz.metrics]
enabled = true

[[fuzz.programs]]
address = "CmyUqWVb4agcavSybreJ7xb7WoKUyWhpkEc6f1DnMEGJ"
program = "target/deploy/sss_token.so"

[[fuzz.programs]]
address = "63pY5GPBHKJ3gu99xTNH9yxUKgp8kUowiiHYzZtaE31E"
program = "target/deploy/sss_transfer_hook.so"
